src/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
	path('', views.board, name='board'),
	path('new_post/', views.new_post, name='new_post'),
	path('<str:sBoardName>/search/', views.search, name='search article'),
	path('hashtag/<str:sTopic>/', views.hashtag, name='hashtag'),
	path('<str:sBoardName>/<str:iSerialNumberOfArticle>/', views.article_detail, name='article detail'),
	path('<str:sBoardName>/', views.board, name='specific board'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('gostar4f1/', include([
        path('management/', include('management.urls')),
        path('tea/', include('teascholarship.urls')),
        # path('cv/', include('usercv.urls')),
        path('activitygroup/', include('ActivityGroup.urls')),
        path('', include('user.urls')),
        path('board/', include('article.urls')),
        path('admin/', admin.site.urls),
        # path('briefcv/', include('briefcv.urls')),
        path('cv/', include('briefcv.urls')),
        path('accounts/', include('allauth.urls')),  # django-allauth網址
    ]))

]
urlpatterns += staticfiles_urlpatterns()

src/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
	path('', views.home, name='home'),
	path('signin_register_tourist/', views.select, name='select'),
	path('user/', views.user, name='user'),
	path('register/', views.register, name='register'),
	path('tourist/', views.tourist, name='tourist'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
	path('user/<str:author>/', views.author, name='author'),
]

src/user/models.py
from django.db import models
from django.contrib.auth.models import User
import os, uuid

def user_directory_path(instance, filename):
	ext = filename.split('.')[-1]
	filename = '{}.{}'.format(uuid.uuid4().hex, ext)
	return os.path.join('avatar', filename)

class UserInfo(models.Model):
	DEPARTMENT_CHOICES = (
		('1', '國文學系'),
		('2', '英語學系'),
		('3', '地理學系'),
		('4', '語言與文化學士原住民專班'),
		('5', '數學系數學組'),
		('6', '數學系應用數學組'),
		('7', '化學系'),
		('8', '物理學系'),
		('9', '生物科技系'),
		('10', '教育學系'),
		('11', '特殊教育學系'),
		('12', '體育學系'),
		('13', '事業經營學系'),
		('14', '運動競技與產業學士原住民專班'),
		('15', '工業科技教育學系科技教育與訓練組'),
		('16', '工業科技教育學系能源與冷凍空調組'),
		('17', '工業設計學系'),
		('18', '光電與通訊工程學系'),
		('19', '電子工程學系'),
		('20', '軟體工程與管理學系'),
		('21', '電機工程學系'),
		('22', '美術學系'),
		('23', '音樂學系'),
		('24', '視覺設計學系'),
		('25', '藝術產業學士原住民專班'),
	)
	GENDER_CHOICES = (
		('1', '男'),
		('2', '女'),
		('3', '其他'),
	)
	iAccount = models.OneToOneField(User, unique = True, verbose_name = '學號', on_delete = models.CASCADE)
	sNickName = models.CharField(max_length = 16, verbose_name = "暱稱", blank = True)
	iArticleNumber = models.PositiveIntegerField(verbose_name = "文章數", blank = True, null = True)	# from 1 to 2,147,483,647
	sShortIntroduction = models.TextField(verbose_name = "短自介", blank = True)
	iScore = models.IntegerField(verbose_name = "積分", null = True, blank = True)
	iReadingScore = models.IntegerField(verbose_name = "閱讀權限", null = True, blank = True)
	# registerDate = models.DateTimeField(verbose_name = "註冊日期", null = True)
	iRegisterDays = models.IntegerField(verbose_name = "註冊天數", null = True, blank = True)
	# iMissingDays = models.IntegerField(verbose_name = "未上線天數", null = True)
	imageAvatar = models.ImageField(upload_to = user_directory_path, default = '', blank = True)
	iDepartment = models.CharField(max_length = 16, verbose_name = "系所", choices = DEPARTMENT_CHOICES, blank = True, null = True)
	iPhone = models.CharField(verbose_name = '電話', max_length = 16, blank = True, null = True)
	iBirthday = models.DateField(verbose_name = '生日', null = True)
	iGender = models.CharField(verbose_name = '性別', max_length = 3, choices = GENDER_CHOICES, blank = True, null = True)

	bShowMyArts = models.BooleanField(verbose_name = '顯示文章', default = True, blank = True, null = True)
	bShowMyCollects = models.BooleanField(verbose_name = '顯示收藏', default = True, blank = True, null = True)
	bShowMyGroups = models.BooleanField(verbose_name = '顯示活動群組', default = True, blank = True, null = True)

	def to_dict(self):
		return {
			'iAccount' : self.iAccount,
			'sNickName': self.sNickName,
			'iArticleNumber': self.iArticleNumber,
			'sShortIntroduction': self.sShortIntroduction,
			'iScore': self.iScore,
			'iReadingScore': self.iReadingScore, 
			# 'registerDate': self.registerDate,
			#'iRegisterDays': self.iRegisterDays,
			# 'iMissingDays': self.iMissingDays,
			'UserName':self.get_full_name(),
			'registerDate':self.date_joined.strftime('%Y-%m-%d'),
			'registerDays':(timezone.now() - self.date_joined).days,
			'offlineDays':(timezone.now() - self.last_login).days,
			'sShortIntroduction':self.sShortIntroduction,
			'iDepartment_grade':self.iDepartment_grade,
			'iPhone':self.iPhone,
			'iBirthday':self.iBirthday,
			'iGender':self.iGender,
		}

src/user/forms.py
from django import forms
from user.models import *
from datetime import datetime
#from captcha.fields import CaptchaField

class RegisterForm(forms.Form):
	DEPARTMENT_CHOICES = (
		(None, '系所'),
		('1', '國文學系'),
		('2', '英語學系'),
		('3', '地理學系'),
		('4', '語言與文化學士原住民專班'),
		('5', '數學系數學組'),
		('6', '數學系應用數學組'),
		('7', '化學系'),
		('8', '物理學系'),
		('9', '生物科技系'),
		('10', '教育學系'),
		('11', '特殊教育學系'),
		('12', '體育學系'),
		('13', '事業經營學系'),
		('14', '運動競技與產業學士原住民專班'),
		('15', '工業科技教育學系科技教育與訓練組'),
		('16', '工業科技教育學系能源與冷凍空調組'),
		('17', '工業設計學系'),
		('18', '光電與通訊工程學系'),
		('19', '電子工程學系'),
		('20', '軟體工程與管理學系'),
		('21', '電機工程學系'),
		('22', '美術學系'),
		('23', '音樂學系'),
		('24', '視覺設計學系'),
		('25', '藝術產業學士原住民專班'),
	)
	GENDER_CHOICES = (
		(None, '性別'),
		('1', '男'),
		('2', '女'),
		('3', '其他'),
	)
	username = forms.CharField(label = "帳號設定", max_length = 128, widget = forms.TextInput(attrs={'id' : 'account','placeholder':'帳號設定'}))
	password1 = forms.CharField(label = "密碼(大於8位)", max_length = 256, widget = forms.PasswordInput(attrs={'id' : 'password1','placeholder':'密碼設定'}))
	password2 = forms.CharField(label = "確認密碼", max_length = 256, widget = forms.PasswordInput(attrs={'id' : 'password2','placeholder':'密碼確認'}))
	name = forms.CharField(label = "姓名", max_length = 16, widget = forms.TextInput(attrs={'id' : 'name','placeholder':'姓名'}))
	department = forms.ChoiceField(label = '系所', choices = DEPARTMENT_CHOICES, widget = forms.Select(attrs={'id': 'department'}))
	email = forms.EmailField(label = "電子信箱", max_length = 256, widget = forms.EmailInput(attrs={'id' : 'mail','placeholder':'電子信箱'}))
	phone = forms.CharField(label = "手機號碼", max_length = 16, widget = forms.TextInput(attrs={'id' : 'phone','placeholder':'手機號碼'}),required = False)
	birthday = forms.DateField(widget = forms.widgets.DateInput(attrs={'type': 'date', 'id': 'birthday'}))
	gender = forms.ChoiceField(label = '性別', choices = GENDER_CHOICES, widget = forms.Select(attrs={'id': 'gender'}))
	# captcha = CaptchaField(error_messages={'invalid': u'驗證碼輸入錯誤'})

class LoginForm(forms.Form):
	username = forms.CharField(label = "帳號", max_length = 128, widget = forms.TextInput(attrs={'id' : 'account','placeholder':'帳號'}))
	password = forms.CharField(label = "密碼", max_length = 256, widget = forms.PasswordInput(attrs={'id' : 'password','placeholder':'密碼'}))

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['imageAvatar']
		

src/user/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django import forms
from user.forms import RegisterForm, LoginForm, UploadImageForm
from django.http import HttpResponse, HttpResponseRedirect
from user.models import UserInfo
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils import timezone
from article.models import *
from ActivityGroup.models import *
from .models import UserInfo
from django.template.defaultfilters import filesizeformat
from src import settings

BASE_URL_PATH = settings.BASE_URL_PATH

def home(request):
	user = request.user
	userList = User.objects.all()
	return render(request, 'user/user_home.html', locals())

def select(request):
	return render(request, 'user/user_signin_register_tourist.html', locals())

def tourist(request):
	return render(request, 'user/user_tourist.html', locals())

def register(request):
	# upon user send the register information
	if request.method == "POST":
		registerForm = RegisterForm(request.POST)

		errors = []
		if not registerForm.is_valid():
			errors.extend(registerForm.errors.values())
			return render(request, 'user/user_register.html', locals())

		else:
			username = registerForm.cleaned_data['username']
			password1 = registerForm.cleaned_data['password1']
			password2 = registerForm.cleaned_data['password2']
			name = registerForm.cleaned_data['name']
			department = registerForm.cleaned_data['department']
			email = registerForm.cleaned_data['email']
			phone = registerForm.cleaned_data['phone']
			# birthday = registerForm.cleaned_data['birthday']
			gender = registerForm.cleaned_data['gender']

		# verify the length of the password
		if (len(password1) < 8):
			errors.append('密碼太短囉！密碼至少8位~')
			return render(request, 'user/user_register.html', locals())
		# verify if password correct
		if password1 != password2:
			errors.append('輸入的密碼不同！')
			return render(request, 'user/user_register.html', locals())
		# verify if the username is student id (all integer)
		try:
			username = str(int(username))
		except Exception as e:
			errors.append('請使用學號註冊。')
			return render(request, 'user/user_register.html', locals())
		# verify if exist same user
		filterSameUser = User.objects.filter(username = username)
		if (len(filterSameUser) > 0):
			errors.append('使用此學號的使用者已存在。')
			return render(request, 'user/user_register.html', locals())

		# if registeration vaild
		user = User()
		user.username = username
		user.set_password(password1)
		user.email = email
		user.first_name = name[0]
		user.last_name = name[1:]
		user.save()
		
		# verify new user
		newUser = auth.authenticate(username = username, password = password1)
		if newUser is not None:
			auth.login(request, newUser)
			userinfo = UserInfo.objects.create(iAccount = newUser)
			userinfo.iDepartment = department
			userinfo.iPhone = phone
			# userinfo.iBirthday = birthday
			userinfo.iGender = gender
			userinfo.save()
			return HttpResponseRedirect('/user/')

	registerForm = RegisterForm(request.POST)
	return render(request, 'user/user_register.html', locals())


def login(request):
	# placeholder
	# return HttpResponse("login page")

	# if user come from somewhere
	nextValue = request.POST.get('next')
	# if user has already logged in
	if request.user.is_authenticated:
		return HttpResponseRedirect('/board/')
	if request.method == "POST":
		loginForm = LoginForm(request.POST)
		errors =''
		if loginForm.is_valid():
			username = loginForm.cleaned_data['username']
			password = loginForm.cleaned_data['password']
			user = auth.authenticate(username = username, password = password)
			if user and user.is_active:
				auth.login(request, user)
				if nextValue != '':
					return redirect(nextValue)
				else:
					return redirect(BASE_URL_PATH+'board/')
			else:
				errors = "Account or password is wrong."
				# if poassword wrong but from otherwhere
				# this is not a good approach cos redirect twice and no errors message
				if nextValue != '':
					return redirect(nextValue)
				else:
					return render(request, 'user/user_login.html', locals())
	loginForm = LoginForm(request.POST)
	return render(request, 'user/user_login.html', locals())

# this shall not exist, delete someday
def logout(request):
	auth.logout(request)
	return render(request, 'user/user_home.html', locals())

@login_required
def user(request):
	intro = request.POST.get('intro')
	arts = request.POST.get('arts')
	collects = request.POST.get('collects')
	groups = request.POST.get('groups')
	# SHOULD handle excption if user has no userinfo!
	user = request.user
	userList = User.objects.all()
	new, old = UserInfo.objects.get_or_create(iAccount = user)
	userinfo = new or old
	if intro:
		userinfo.sShortIntroduction = intro
		userinfo.save()
		return redirect("/user/")

	if arts:
		if arts == 'open':
			userinfo.bShowMyArts = 'True'
			userinfo.save()
		else:
			userinfo.bShowMyArts = 'False'
			userinfo.save()
		return redirect("/user/")

	if collects:
		if collects == 'open':
			userinfo.bShowMyCollects = 'True'
			userinfo.save()
		else:
			userinfo.bShowMyCollects = 'False'
			userinfo.save()
		return redirect("/user/")

	if groups:
		if groups == 'open':
			userinfo.bShowMyGroups = 'True'
			userinfo.save()
		else:
			userinfo.bShowMyGroups = 'False'
			userinfo.save()
		return redirect("/user/")

	# article that the user posted
	articleList = Article.objects.filter(sAuthor = user, bIsInEdtion = False)
	userinfo.iArticleNumber = len(articleList)
	userinfo.save()

	form = UploadImageForm()
	if request.method == "POST":
		form = UploadImageForm(request.POST, request.FILES)
		if form.is_valid():
			userinfo.imageAvatar.delete()
			userinfo.imageAvatar = form.cleaned_data['imageAvatar']
			userinfo.save()
			return redirect("/user/")
	else:
		form = UploadImageForm()

	userinfo = {
		'user':user,
		'UserName':user.get_full_name(),
		'sNickName':userinfo.sNickName,
		'article_number':userinfo.iArticleNumber,
		'score':userinfo.iScore,
		'read':userinfo.iReadingScore,
		'register':user.date_joined.strftime('%Y-%m-%d'),
		'registerDays':(timezone.now() - user.date_joined).days,
		'offlineDays':(timezone.now() - user.last_login).days,
		'intro':userinfo.sShortIntroduction,
		'bShowMyArts':userinfo.bShowMyArts,
		'bShowMyCollects':userinfo.bShowMyCollects,
		'bShowMyGroups':userinfo.bShowMyGroups,
		}
	

	# 發表的文章
	postedArticles = {'article': articleList}
	# 參與的活動群組
	activityGroups = [group.idOfGroup for group in UserOfActivityGroup.objects.filter(iUserAccount = user)]
	joinedGroups = {'activityGroups': activityGroups}
	# 收藏的文章
	collectArticle = [article.iSerialNumberOfArticle for article in UserCollectArticle.objects.filter(iAccount = user)]

	# 把字典合在一起
	context = {**userinfo, **postedArticles, **joinedGroups, 'collectArticle':collectArticle, 'form':form, "user":user, "userList":userList}
	
	return render(request, 'user/user_user.html', context)

def author(request, author):
	user = request.user
	userList = User.objects.all()
	author = User.objects.get(username = author)

	if author == user:
		return redirect('/user')

	authorinfo = {
		'UserName':author.get_full_name(),
		'sNickName':author.userinfo.sNickName,
		'article_number':author.userinfo.iArticleNumber,
		'score':author.userinfo.iScore,
		'read':author.userinfo.iReadingScore,
		'register':author.date_joined.strftime('%Y-%m-%d'),
		'registerDays':(timezone.now() - author.date_joined).days,
		'offlineDays':(timezone.now() - author.last_login).days,
		'intro':author.userinfo.sShortIntroduction,
		'bShowMyArts':author.userinfo.bShowMyArts,
		'bShowMyCollects':author.userinfo.bShowMyCollects,
		'bShowMyGroups':author.userinfo.bShowMyGroups,
		}
	# 發表的文章
	articleList = Article.objects.filter(sAuthor = author, bIsInEdtion = False)
	postedArticles = {'article': articleList}
	# 參與的活動群組
	activityGroups = [group.idOfGroup for group in UserOfActivityGroup.objects.filter(iUserAccount = author)]
	joinedGroups = {'activityGroups': activityGroups}
	# 收藏的文章
	collectArticle = [article.iSerialNumberOfArticle for article in UserCollectArticle.objects.filter(iAccount = author)]

	# 把字典合在一起
	context = {**authorinfo, **postedArticles, **joinedGroups, 'collectArticle':collectArticle, 'author':author}
	
	return render(request, 'user/user_author.html', context)

src/user/templates/user/user_home.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <!-- 載入思源黑體 -->
    <title>GoStar4.0</title>
    <style>
        
        body {
            margin: 0;
        }

        span {
            font-size: 14pt;
            font-weight: 700;
            font-family: 'Noto Sans TC', '微軟正黑體', 'Microsoft JhengHei', sans-serif;
            color: white;
            position: absolute;
        }

        #bg {
            position: absolute;
            width: 100%;
            height: 100%;
        }

        #logo {
            position: absolute;
            width: 19%;
            height: 47%;
            left: 2.5%;
            top: 1%;
        }

        #student {
            position: absolute;
            width: 18%;
            height: 33%;
            left: 34.5%;
            top: 4.5%;
            
        }

        #teacher {
            position: absolute;
            width: 24.3%;
            height: 30%;
            left: 73.5%;
            top: 1%;
        }

        #tea_student {
            position: absolute;
            width: 11.32%;
            height: 20.1%;
            left: 70.5%;
            top: 47.7%;
        }

        #teach_student {
            position: absolute;
            width: 20.3%;
            height: 36.1%;
            left: 60.3%;
            top: 27.1%;
        }

        #staff {
            position: absolute;
            width: 13.67%;
            height: 24.3%;
            left: 16.75%;
            top: 30.35%;
        }

        #free_student {
            position: absolute;
            width: 8%;
            height: 16%;
            left: 81%;
            top: 41%;
        }

        #student:hover, #teacher:hover, #tea_student:hover, #teach_student:hover, #staff:hover, #free_student:hover {
            -webkit-filter: drop-shadow(12px 12px 7px rgba(242, 252, 200, 0.1));
            filter: drop-shadow(12px 12px 7px rgba(242, 252, 200, 0.1));
        }

    </style>
</head>

<body>
    <img src="{% static 'user/img/home/背景-01.jpg' %}" id="bg" />
    <img src="{% static 'user/img/home/標題.png' %}" id="logo" />
    <a href="{%if user in userList%}{% url 'article:board' %}{%else%}{% url 'user:select' %}{%endif%}">
        <img src="{% static 'user/img/home/1.師就處主頁面-02.png' %}" id="student" />
        <span style="top: 35%;left: 40%;">一般訪客</span>
    </a>
    <a href="{%if user in userList%}{% url 'article:board' %}{%else%}{% url 'user:select' %}{%endif%}">
        <img src="{% static 'user/img/home/1.師就處主頁面-10.png' %}" id="teacher" />
        <span style="top: 26%;left: 83%;">教師</span>
    </a>
    <a href="{%if user in userList%}{% url 'article:board' %}{%else%}{% url 'user:select' %}{%endif%}">
        <img src="{% static 'user/img/home/1.師就處主頁面-08.png' %}" id="teach_student" />
        <span style="top: 56%;left: 66%;">師資生</span>
    </a>
    <a href="{%if user in userList%}{% url 'article:board' %}{%else%}{% url 'user:select' %}{%endif%}">
        <img src="{% static 'user/img/home/1.師就處主頁面-12.png' %}" id="tea_student" />
        <span style="top: 61.5%;left: 74%;">師獎生</span>
    </a>
    <a href="{%if user in userList%}{% url 'article:board' %}{%else%}{% url 'user:select' %}{%endif%}">
        <img src="{% static 'user/img/home/1.師就處主頁面-04.png' %}" id="staff" />
        <span style="top: 50%;left: 20.5%;">行政人員</span>
    </a>
    <a href="{%if user in userList%}{% url 'article:board' %}{%else%}{% url 'user:select' %}{%endif%}">
        <img src="{% static 'user/img/home/1.師就處主頁面-06.png' %}" id="free_student" />
        <span style="top: 52.5%;left: 82.7%;">公費生</span>
    </a>
    
    
    
    
    
    
</body>

</html>

src/user/templates/user/user_signin_register_tourist.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <style>
        body {
            margin: 0;
        }

        #bg {
            position: absolute;
            width: 100%;
            height: 100%;
        }

        #logo {
            position: absolute;
            width: 6.215%;
            height: 15.5%;
            left: 1.78%;
            top: 3.45%;
            cursor: pointer;
        }

        #register {
            position: absolute;
            width: 23.35%;
            height: 28.266666%;
            left: 11.5%;
            top: 42%;
            cursor: pointer;
        }

        #signIn {
            position: absolute;
            width: 23.35%;
            height: 28.266666%;
            left: 39%;
            top: 42%;
            cursor: pointer;
        }

        #tourist {
            position: absolute;
            width: 23.35%;
            height: 28.266666%;
            left: 66.5%;
            top: 42%;
            cursor: pointer;
        }

        #select_1 {
            position: absolute;
            width: 22.175%;
            height: 14.266666%;
            left: 12%;
            top: 41%;
            display: none;
            opacity: 50%;
        }

        #select_2 {
            position: absolute;
            width: 22.175%;
            height: 14.266666%;
            left: 39.5%;
            top: 41%;
            display: none;
            opacity: 50%;
        }

        #select_3 {
            position: absolute;
            width: 22.175%;
            height: 14.266666%;
            left: 67%;
            top: 41%;
            display: none;
            opacity: 50%;
        }
    </style>
    <script type="text/javascript">
        var se_1, se_2, se_3;
        function select_1() {
            se_1 = document.getElementById('select_1');
            se_1.style.display = 'block';
        }
        function noselect_1() {
            se_1 = document.getElementById('select_1');
            se_1.style.display = 'none';
        }
        function select_2() {
            se_2 = document.getElementById('select_2');
            se_2.style.display = 'block';
        }
        function noselect_2() {
            se_2 = document.getElementById('select_2');
            se_2.style.display = 'none';
        }
        function select_3() {
            se_3 = document.getElementById('select_3');
            se_3.style.display = 'block';
        }
        function noselect_3() {
            se_3 = document.getElementById('select_3');
            se_3.style.display = 'none';
        }
    </script>

</head>

<body>
    <img src="{% static 'user/img/home/BG-01.jpg' %}" id="bg" />
    <a href="{% url 'user:home' %}"><img src="{% static 'user/img/home/LOGO.png' %}" id="logo"/></a>
    <a href="#"><img src="{% static 'user/img/home/選定ICON.png' %}" id="select_1"
        onmousemove="select_1();" onmouseout="noselect_1();" /></a>
    <a href="{% url 'user:login' %}"><img src="{% static 'user/img/home/選定ICON.png' %}" id="select_2"
        onmousemove="select_2();" onmouseout="noselect_2();" /></a>
    <a href="{% url 'user:tourist' %}"><img src="{% static 'user/img/home/選定ICON.png' %}" id="select_3"
        onmousemove="select_3();" onmouseout="noselect_3();" /></a>
    <a href="{% url 'user:register' %}"><img src="{% static 'user/img/home/註冊ICON.png' %}" id="register" onmousemove="select_1();"
        onmouseout="noselect_1();" /></a>
    <a href="{% url 'user:login' %}"><img src="{% static 'user/img/home/登入ICON.png' %}" id="signIn" onmousemove="select_2();"
        onmouseout="noselect_2();" /></a>
    <a href="{% url 'user:tourist' %}"><img src="{% static 'user/img/home/遊客ICON.png' %}" id="tourist" onmousemove="select_3();"
        onmouseout="noselect_3();" /></a>
    
</body>

</html>

src/user/templates/user/user_tourist.html
{% load static %}
<style>
    body {
        margin: 0;
        color: white;
    }

    #bg {
        position: absolute;
        width: 100%;
        height: 100%;
    }

    #logo {
            position: absolute;
            width: 6.2%;
            height: 15.3%;
            left: 1.785%;
            top: 3.45%;
            cursor: pointer;
        }

    #sign_in {
        position: absolute;
        top: 58%;
        left: 46%;
        width: 7.049%;
        height: 7.26666%;
        border: none;
        background-image:url("{% static 'user/img/遊客拜訪/還沒按.png' %}");
        background-size: 100% 100%;
        background-color: transparent;
        cursor: pointer;
    }

    #sign_in:hover {
        background-image:url("{% static 'user/img/遊客拜訪/按下去的反應.png' %}");
    }

</style>
<img src="{% static 'user/img/遊客拜訪/BG-01.jpg' %}" id="bg" />
<a href="{% url 'home' %}"><img src="{% static 'user/img/home/LOGO.png' %}" id="logo" /></a>

<button type="submit" onclick="location.href='/board'" id="sign_in"></button>