src/article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
	path('', views.board, name='board'),
	path('new_post/', views.new_post, name='new_post'),
	path('<str:sBoardName>/search/', views.search, name='search article'),
	path('hashtag/<str:sTopic>/', views.hashtag, name='hashtag'),
	path('<str:sBoardName>/<str:iSerialNumberOfArticle>/', views.article_detail, name='article detail'),
	path('<str:sBoardName>/', views.board, name='specific board'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('gostar4f1/', include([
        path('management/', include('management.urls')),
        path('tea/', include('teascholarship.urls')),
        # path('cv/', include('usercv.urls')),
        path('activitygroup/', include('ActivityGroup.urls')),
        path('', include('user.urls')),
        path('board/', include('article.urls')),
        path('admin/', admin.site.urls),
        # path('briefcv/', include('briefcv.urls')),
        path('cv/', include('briefcv.urls')),
        path('accounts/', include('allauth.urls')),  # django-allauth網址
    ]))

]
urlpatterns += staticfiles_urlpatterns()

src/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
	path('', views.home, name='home'),
	path('signin_register_tourist/', views.select, name='select'),
	path('user/', views.user, name='user'),
	path('register/', views.register, name='register'),
	path('tourist/', views.tourist, name='tourist'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
	path('user/<str:author>/', views.author, name='author'),
]

src/article/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import User

class Board(models.Model):
	idOfBoard = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
	sBoardName = models.CharField(verbose_name = '版塊名稱', max_length = 128, unique = True)
	sDescription = models.TextField(verbose_name = '敘述及版規', blank = True)
	
	def __str__(self):
		return '%s' % (self.sBoardName, )

class Article(models.Model):
	sAuthor = models.ForeignKey(User, verbose_name = '作者', on_delete = models.SET_NULL, null = True)
	iSerialNumberOfArticle = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
	sTitle = models.CharField(verbose_name = '文章標題', max_length = 128, unique = True)
	sContent = models.TextField(verbose_name = '文章內容')
	# 實作時應存當時時間
	ArticlePostTime = models.DateTimeField(verbose_name = '張貼時間', default = timezone.now)
	# 是否在編輯中(未送出)
	bIsInEdtion = models.BooleanField(default = True)
	# 討論熱度
	iTrending = models.FloatField(default = 0, null = True)
	whichBoard = models.ForeignKey(Board, verbose_name = "所在板塊", on_delete = models.SET_NULL, null = True)
	likeArticleNumber = models.PositiveIntegerField(verbose_name = "按讚數", blank = True, null = True)
	commentNumber = models.PositiveIntegerField(verbose_name = "留言數", blank = True, null = True)

	def __str__(self):
		return '%s by %s' % (self.sTitle, self.sAuthor.get_full_name())

# class BoardOfArticle(models.Model):
# 	idOfBoard = models.ForeignKey(Board, on_delete = models.CASCADE)
# 	iSerialNumberOfArticle = models.ForeignKey(Article, on_delete = models.CASCADE)

class TopicTag(models.Model):
	idOfTopic = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4)
	sTopic = models.CharField(verbose_name = '話題標籤', max_length = 128)

	def __str__(self):
		return self.sTopic

class ArticleOfTopicTag(models.Model):
	iSerialNumberOfArticle = models.ForeignKey(Article, on_delete = models.CASCADE)
	idOfTopic = models.ForeignKey(TopicTag, on_delete = models.CASCADE)

# 使用者留言文章
class CommentOfArticle(models.Model):
	iSerialNumberOfArticle = models.ForeignKey(Article, on_delete = models.CASCADE)
	iAccount = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
	idOfComment = models.CharField(max_length = 36, primary_key = True, default = uuid.uuid4, editable = False)
	CommentTime = models.DateTimeField(verbose_name = '留言時間', default = timezone.now, editable = False)
	sContentOfComment = models.TextField(verbose_name = '留言內容')
	likeCommentNumber = models.PositiveIntegerField(verbose_name = "按讚數", blank = True, null = True)

	def __str__(self):
		return '%s 留言在 %s' % (self.iAccount, self.iSerialNumberOfArticle)

# 使用者收藏文章
class UserCollectArticle(models.Model):
	iSerialNumberOfArticle = models.ForeignKey(Article, on_delete = models.CASCADE)
	iAccount = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return '%s 收藏 %s' % (self.iAccount, self.iSerialNumberOfArticle)

# 使用者按讚文章
class UserLikesArticle(models.Model):
	iSerialNumberOfArticle = models.ForeignKey(Article, on_delete = models.CASCADE)
	iAccount = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return '%s 按讚 %s' % (self.iAccount, self.iSerialNumberOfArticle)

# 使用者按讚留言
class UserLikesComment(models.Model):
	commentofArticle = models.ForeignKey(CommentOfArticle, on_delete = models.CASCADE)
	iAccount = models.ForeignKey(User, on_delete = models.CASCADE)

src/article/forms.py
from django import forms
from article.models import *
from django.forms import CharField, ModelMultipleChoiceField, ModelChoiceField

class ArticleNewPostForm(forms.Form):
	sBoardName = forms.ModelChoiceField(label = '發文版塊', queryset = Board.objects.all().order_by('-idOfBoard'), widget = forms.Select(attrs={'id':'selectboard' }))
	sTitle = forms.CharField(label = '標題', widget = forms.TextInput(attrs={'id' : 'title','placeholder':'標題'}))
	sContent = forms.CharField(label = '內文', widget = forms.Textarea(attrs={'class' : 'text','placeholder':'內文'}))

src/article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from article.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from ActivityGroup.models import *
from user.models import *
from article.forms import *
import uuid
from django.db.models import Q

def board(request, sBoardName = 'all'):
	user = request.user
	userList = User.objects.all()
	if user in userList:
		user = User.objects.get(username = user)
	boardList = list(Board.objects.all().order_by('-idOfBoard'))
	if (sBoardName == 'all'):
		# 取出所有文章
		articleList = list(Article.objects.filter(bIsInEdtion = False).order_by('-ArticlePostTime'))
		# 取出所有hashtag
		TagList = list(TopicTag.objects.all())
	else:
		# 取出該板塊文章
		uuidOfBoard = Board.objects.get(sBoardName = sBoardName)
		articleList = list(Article.objects.filter(whichBoard = uuidOfBoard, bIsInEdtion = False).order_by('-ArticlePostTime'))
		groupList = list(ActivityGroup.objects.filter(whichBoard = uuidOfBoard).order_by('-createdTime'))
		# 取出板塊文章之hashtag
		TagList =[]
		Topic = []
		for article in articleList:
			if (ArticleOfTopicTag.objects.filter(iSerialNumberOfArticle = article)):
				TagList = list(set(TagList).union(set(list(ArticleOfTopicTag.objects.filter(iSerialNumberOfArticle = article)))))
				for i in TagList:
					Topic.append(i.idOfTopic)
		Topic = list(set(Topic))

	for article in articleList:
		article.likeArticleNumber = len(UserLikesArticle.objects.filter(iSerialNumberOfArticle = article))
		article.commentNumber = len(CommentOfArticle.objects.filter(iSerialNumberOfArticle = article))
		article.save()
				
	return render(request, 'article/article_board.html', locals())

def search(request, sBoardName = 'all'):
	user = request.user
	userList = User.objects.all()
	search = request.GET.get('search')
	boardList = list(Board.objects.all().order_by('-idOfBoard'))
	# 取出標題內文含搜尋文字之文章
	if (sBoardName == 'all'):
		articleList = list(Article.objects.filter(Q(sTitle__contains = search, bIsInEdtion = False)|Q(sContent__contains = search, bIsInEdtion = False)).order_by('-ArticlePostTime'))
	else:
		uuidOfBoard = Board.objects.get(sBoardName = sBoardName)
		articleList = list(Article.objects.filter(Q(whichBoard = uuidOfBoard, sTitle__contains = search, bIsInEdtion = False)|Q(whichBoard = uuidOfBoard, sContent__contains = search, bIsInEdtion = False)).order_by('-ArticlePostTime'))
	pieceOfdata = len(articleList)

	return render(request, 'article/article_board.html', locals())

def hashtag(request, sTopic = 1):
	user = request.user
	userList = User.objects.all()
	boardList = list(Board.objects.all().order_by('-idOfBoard'))
	if (sTopic == 1):
		return redirect('/board')
	try:
		topic = TopicTag.objects.get(sTopic = sTopic)
	except:
		return HttpResponse("該文章或板塊不存在")

	articleList = list(ArticleOfTopicTag.objects.filter(idOfTopic = topic))
	articleList = list(article.iSerialNumberOfArticle for article in articleList)

	return render(request, 'article/article_board.html', locals())

def article_detail(request, sBoardName = 1, iSerialNumberOfArticle = 1):
	user = request.user
	userList = User.objects.all()
	boardList = list(Board.objects.all().order_by('-idOfBoard'))
	if (sBoardName == 1 and iSerialNumberOfArticle == 1):
		return redirect('/board')
	try:
		board = Board.objects.get(sBoardName = sBoardName)
		article = Article.objects.get(iSerialNumberOfArticle = iSerialNumberOfArticle)
	except:
		return HttpResponse("該文章或板塊不存在")

	# 新留言
	comment = request.POST.get('comment')
	action = request.GET.get('action')
	warn = request.GET.get('warn')
	
	author = User.objects.get(username = article.sAuthor)
	# 以下再加入需要的文章作者資訊（UserInfo）
	# authorinfo = {
	# 	'UserName':author.get_full_name(),
	# 	'sNickName':author.userinfo.sNickName,
	# 	'article_number':author.userinfo.iArticleNumber,
	# 	'score':author.userinfo.iScore,
	# 	'read':author.userinfo.iReadingScore,
	# 	'register':author.date_joined.strftime('%Y-%m-%d'),
	# 	'registerDays':(timezone.now() - author.date_joined).days,
	# 	'offlineDays':(timezone.now() - author.last_login).days,
	# 	'intro':author.userinfo.sShortIntroduction,
	# 	}

	# 取出文章留言
	commentList = list(CommentOfArticle.objects.filter(iSerialNumberOfArticle = article).order_by('-CommentTime'))
	commentUser = list(CommentOfArticle.iAccount for CommentOfArticle in commentList)
	commentNumber = len(commentList)
	for com in commentList:
		com.likeCommentNumber = len(UserLikesComment.objects.filter(commentofArticle = com))
		com.save()
	
	# 取出按讚文章的user
	heart = list(UserLikesArticle.objects.filter(iSerialNumberOfArticle = article))
	ULArticle = list(UserLikesArticle.iAccount for UserLikesArticle in heart)
	# 取出收藏文章的user
	CLA = list(UserCollectArticle.objects.filter(iSerialNumberOfArticle = article))
	CLArticle = list(UserCollectArticle.iAccount for UserCollectArticle in CLA)
	# 取出文章之hashtag
	TAG = list(ArticleOfTopicTag.objects.filter(iSerialNumberOfArticle = article))
	
	# 取出按讚的留言
	if user in userList:
		userlikescomment = UserLikesComment.objects.filter(iAccount = user)
		userlikescomment = [userlikescomment.commentofArticle for userlikescomment in userlikescomment]

	# 按讚文章
	if action == 'like':
		like, isNew = UserLikesArticle.objects.get_or_create(iAccount = user,iSerialNumberOfArticle = article)
		if isNew != True:
			like.delete()	
		article.likeArticleNumber = len(UserLikesArticle.objects.filter(iSerialNumberOfArticle = article))
		article.save()
		return redirect('/board/%s/%s' % (sBoardName, iSerialNumberOfArticle))
	# 收藏文章
	if action == 'collect':	
		collection, isNew = UserCollectArticle.objects.get_or_create(iAccount = user,iSerialNumberOfArticle = article)
		if isNew != True:
			collection.delete()
		return redirect('/board/%s/%s' % (sBoardName, iSerialNumberOfArticle))
	# 新增留言
	if comment:
		CommentOfArticle.objects.create(iAccount = user, sContentOfComment = comment, iSerialNumberOfArticle = article)
		article.commentNumber = len(CommentOfArticle.objects.filter(iSerialNumberOfArticle = article))
		article.save()
		return redirect('/board/%s/%s' % (sBoardName, iSerialNumberOfArticle))
	# 按讚留言
	if request.GET.get('like_comment') != None:
		idOfComment = request.GET.get('like_comment')
		comment = CommentOfArticle.objects.get(pk = idOfComment)
		like, isNew = UserLikesComment.objects.get_or_create(commentofArticle = comment, iAccount = user)
		if isNew != True:
			like.delete()
		return redirect('/board/%s/%s' % (sBoardName, iSerialNumberOfArticle))
		
	return render(request, 'article/article_article_detail.html', locals())

@login_required
def new_post(request):
	user = request.user
	userList = User.objects.all()
	article = ''
	# get last edited article if exits one, otherwise create new one.
	if len(Article.objects.filter(bIsInEdtion = True, sAuthor = user)) == 0:
		article = Article.objects.create(bIsInEdtion = True, sAuthor = user, sTitle = '%s的新文章' % (user))
	else:
		article = Article.objects.get(bIsInEdtion = True, sAuthor = user)

	if article.sContent:
		sTitle = article.sTitle
	else:
		sTitle = ''

	data = {
		'sTitle' : sTitle,
		'sContent' : article.sContent,
		'sBoardName' : article.whichBoard,
		'sTag' : [topic.idOfTopic for topic in ArticleOfTopicTag.objects.filter(iSerialNumberOfArticle = article)],
	}

	articleNewPostform = ArticleNewPostForm(initial = data)
	articleList = [article.sTitle.lower() for article in Article.objects.all()]
	articleList.remove(article.sTitle.lower())

	topicList = TopicTag.objects.all()
	topicListName = [topic.sTopic for topic in topicList]
	oldtopicList = [topic.idOfTopic for topic in ArticleOfTopicTag.objects.filter(iSerialNumberOfArticle = article)]
	oldtopicListName = [topic.sTopic for topic in oldtopicList]
	
	action = request.POST.get('action')
	if action:
		choice = request.POST.getlist('select_tag')
		articleNewPostform = ArticleNewPostForm(request.POST, initial = data)
		if articleNewPostform.has_changed():
			articleNewPostform.is_valid()
			sBoardName = articleNewPostform.cleaned_data['sBoardName']
			sTitle = articleNewPostform.cleaned_data['sTitle']
			if (sTitle.lower() in articleList): 
			 	error = '您輸入的內容與現有重複了！'
			 	articleNewPostform = ArticleNewPostForm(request.POST)
			 	return render(request, 'article/article_new_post.html', locals())
			else:
				sContent = articleNewPostform.cleaned_data['sContent']
				Article.objects.filter(bIsInEdtion = True, sAuthor = user).update(sTitle = sTitle, sContent = sContent, whichBoard = sBoardName)

		for i in choice:
			if i not in oldtopicListName:
				if i in topicListName:
					topic = TopicTag.objects.get(sTopic = i)
				else:
					topic = TopicTag.objects.create(sTopic = i)
				ArticleOfTopicTag.objects.create(iSerialNumberOfArticle = article, idOfTopic = topic)
		for i in oldtopicListName:
			if i not in choice:
				topic = TopicTag.objects.get(sTopic = i)
				ArticleOfTopicTag.objects.get(iSerialNumberOfArticle = article, idOfTopic = topic).delete()

		if action == 'send':
			articleNewPostform.is_valid()
			sBoardName = articleNewPostform.cleaned_data['sBoardName']
			sTitle = articleNewPostform.cleaned_data['sTitle']
			Article.objects.filter(bIsInEdtion = True, sAuthor = user).update(bIsInEdtion = False)
			return redirect('/board/%s/%s/' % (sBoardName, iSerialNumberOfArticle))


	# if action == 'send':
	# 	articleNewPostform = ArticleNewPostForm(request.POST)
	# 	if articleNewPostform.has_changed():
	# 		articleNewPostform.is_valid()
	# 		sBoardName = articleNewPostform.cleaned_data['sBoardName']
	# 		sTitle = articleNewPostform.cleaned_data['sTitle']
	# 		if (sTitle in articleList): 
	# 		 	error = '您輸入的內容與現有重複了'
	# 		 	articleNewPostform = ArticleNewPostForm(request.POST)
	# 		 	return render(request, 'article/article_new_post.html', locals())
	# 		sContent = articleNewPostform.cleaned_data['sContent']
	# 		Article.objects.filter(bIsInEdtion = True, sAuthor = user).update(sTitle = sTitle, sContent = sContent, whichBoard = sBoardName, bIsInEdtion = False)

src/article/templates/article/article_base.html
{% load static %}
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
<!-- 載入思源黑體 -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <TITLE>{% block title %}{% endblock %}</TITLE>
    <style>
        body {
            margin: 0;
            overflow: hidden;
            font-family: 'Noto Sans TC', '微軟正黑體', 'Microsoft JhengHei', sans-serif;
            color: #ffffff;
        }

        body::-webkit-scrollbar {
            display: none;
        }

        a {
            text-decoration:none;
        }

        #bg {
            position: absolute;
            width: 100%;
            height: 100%;
            background-image: url("{% static 'article/img/論壇/背景-01.jpg' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }

        #logo {
            position: absolute;
            width: 6.2%;
            height: 15.3%;
            left: 1.785%;
            top: 3.45%;
            background-image: url("{% static 'article/img/論壇/LOGO.png' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }

        #person {
            position: absolute;
            width: auto;
            height: 5.0666%;
            top: 3%;
            right: 15.5%;
        }

        #person span {
            position: relative;
            bottom: 30%;
            font-size: 12pt;
            color: #ffffff;
        }

        #person img {
            position: relative;
            width: 30px;
            height: 100%;
            border-radius: 50%;
            border: #ecd7ff 1.5px solid;
        }

        #activity_bt {
            position: absolute;
            top: 3%;
            right: 12%;
            width: 2.6%;
            height: 5.06666%;
            background-image: url("{% static 'article/img/論壇/活動群組.png' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }

        #cv_bt {
            position: absolute;
            top: 3%;
            right: 8.5%;
            width: 2.6%;
            height: 5.06666%;
            background-image: url("{% static 'article/img/論壇/公開履歷.png' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }

        #notice_bar {
            position: absolute;
            top: 2.6%;
            right: 1.2%;
            width: 18%;
            height: 92%;
            background-image: url("{% static 'article/img/論壇/通知/通知底.png' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
            display: none;
        }

        #notice {
            position: absolute;
            top: 3.9%;
            right: 5%;
            width: 2.65%;
            height: 2.755555%;
            cursor: pointer;
        }

        #set_bar {
            position: absolute;
            top: 2.6%;
            right: 1.3%;
            width: 10%;
            height: 92%;
            background-image: url("{% static 'article/img/論壇/功能列/功能列底.png' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
            display: none;
        }

        #set {
            position: absolute;
            top: 4%;
            right: 2%;
            width: 1.75%;
            height: 2.311111%;
            cursor: pointer;
        }

        .function_choice {
            position:relative;
            top: 9%;
            width: 100%;
            height: 27px;
        }

        .function_choice:hover {
            background-image: url("{% static 'article/img/論壇/功能列/功能列選單選定.png' %}");
            background-repeat: no-repeat;
            background-size: 100% 100%;
            cursor: pointer;
        }

        .function_choice a, .function_choice span {
            position:absolute;
            right: 7%;
            font-size: 13pt;
            font-weight: 700;
            color: #ffffff;
        }

 
    </style>
    <script>
        var bar;
        function function_bar() {
            bar = document.getElementById("set_bar");
            if (bar.style.display == "block") {
                bar.style.display = "none";
            }
            else {
                bar.style.display = "block"
            }
        }
        function notice_bar() {
            bar = document.getElementById("notice_bar");
            if (bar.style.display == "block") {
                bar.style.display = "none";
            }
            else {
                bar.style.display = "block"
            }
        }
    </script>
</head>

<body>
    <div id="bg"></div>
    
    {% block content %}
    {% endblock %}
    
    <a href="/board/" id="logo"></a>

    <div id="person">
        <img src="{% if user.userinfo.imageAvatar %}{{user.userinfo.imageAvatar.url}}{% endif %}">
        <span>{{user.username}}</span>
    </div>
    
    <a href="/activitygroup/" id="activity_bt"></a>
    <a href="/cv/public" id="cv_bt"></a>
    
    <div id="notice_bar">
        <!-- 通知列尚未完成 -->
    </div>
    <img id="notice" src="{% static 'article/img/論壇/通知.png' %}" onclick="notice_bar();">
    
    <div id="set_bar">
        {%if user in userList%}
        <div class="function_choice"><a href="{% url 'user:user' %}">個人頁面</a></div>
        <div class="function_choice"><a href="/cv/mycv">履歷管理</a></div>
        <div class="function_choice"><span>主題變色</span></div>
        <div class="function_choice"><span>音樂</span></div>
        <div class="function_choice"><a href="{% url 'user:logout' %}">登出</a></div>
        {%else%}
        <div class="function_choice"><a href="{% url 'user:login' %}">登入</a></div>
        {%endif%}
    </div>
    <img id="set" src="{% static 'article/img/論壇/功能列-02.png' %}" onclick="function_bar();">
    
</body>

<footer>

</footer>

</html>